services:
  jenkins:
    build: ./jenkins
    container_name: socket-jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    environment:
      - SOCKET_SECURITY_API_TOKEN=${SOCKET_SECURITY_API_TOKEN}
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/casc:/var/jenkins_home/casc_configs
    restart: unless-stopped

  mongo:
    image: mongo:4.4
    container_name: jenkins-mongodb
    user: mongodb
    expose:
      - 27017
    volumes:
      - mongodb_data:/data/db

volumes:
  jenkins_home:
  mongodb_data:
